#!/bin/sh
echo "Compiling haXe code"
haxe compile.hxml

#echo "Copying Include Files (css,js,tpl etc.)"
rsync --delete -a includes/* php/

#echo "Creating the documentation"
cd doc
haxedoc output.xml > /dev/null
cd ..