#!/bin/sh

#echo "Copying Include Files (css,js,tpl etc.)"
rsync --delete -a includes/ php/

echo "Compiling haXe code"
haxe compile.hxml

#echo "Creating the documentation"
cd doc
haxedoc output.xml > /dev/null
cd ..
